// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CollapseComments
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCollapseCommandPackageString = "02438993-d9fa-42ae-b30e-c4058e2136b3";
        public static Guid guidCollapseCommandPackage = new Guid(guidCollapseCommandPackageString);

        public const string guidCollapseCommandPackageCmdSetString = "fafe8ebd-e623-491e-8e27-5543153918c8";
        public static Guid guidCollapseCommandPackageCmdSet = new Guid(guidCollapseCommandPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CollapseCommandId = 0x0100;
        public const int ExpandCommandId = 0x0200;
        public const int ToggleCommandId = 0x0300;
    }
}