// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CollapseComments
{
    internal sealed partial class Vsix
    {
        public const string Id = "CollapseComments.a1dfaad6-6e8d-420a-807b-ebbbc0e7a6bf";
        public const string Name = "Collapse Comments";
        public const string Description = @"Improve the way you work with comments in code by easily (& automatically) expanding and collapsing comments.";
        public const string Language = "en-US";
        public const string Version = "2.2";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
    }
}
